dist: xenial
language: python
python:
  - "3.7"

# command to install dependencies and the package itself
install:
  - source .ci/install_conda.sh
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION xtensor-python
  - source activate test-environment
  - pip install .

# command to run tests
script: py.test .