language: python
python:
  - "3.7"
  - "3.8"

# command to install dependencies and the package itself
install:
  - source .ci/install_conda.sh
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION xtensor-python -c conda-forge
  - conda activate test-environment
  - python -m pip install .

# command to run tests
script: py.test .